# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbr2x2_q0MquJRF0jxHNwqdr97bCBBM9
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
from collections import defaultdict


log_file = "fsm_log.csv"

df = pd.read_csv(log_file, header=None,
                 names=["timestamp", "user", "current_state", "event", "next_state"])


transition_counts = defaultdict(lambda: defaultdict(int))


for _, row in df.iterrows():
    from_state = row["current_state"]
    to_state = row["next_state"]
    transition_counts[from_state][to_state] += 1


transition_probabilities = []

for from_state, transitions in transition_counts.items():
    total = sum(transitions.values())
    for to_state, count in transitions.items():
        probability = count / total
        transition_probabilities.append({
            "From": from_state,
            "To": to_state,
            "Count": count,
            "Probability": round(probability, 4)
        })


result_df = pd.DataFrame(transition_probabilities)
print("Markov Transition Probability Matrix:\n")
print(result_df)